server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: micro-oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.184.197:8848
    gateway:
      routes: #配置路由规则
        - id: oauth2-api-route
          uri: lb://micro-oauth2-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-route
          uri: lb://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: oauth2-manager-route
          uri: lb://medical-provider-manager
          predicates:
            - Path=/manager/**
        - id: oauth2-shop-route
          uri: lb://medical-consumer-shop
          predicates:
            - Path=/shop/**
        - id: oauth2-user-route
          uri: lb://medical-provider-user
          predicates:
            - Path=/user/**
        - id: oauth2-consultation-route
          uri: lb://medical-provider-consultation
          predicates:
            - Path=/consultation/**
        - id: oauth2-encyclopedias-route
          uri: lb://medical-provider-encyclopedias
          predicates:
            - Path=/encyclopedias/**
        - id: oauth2-doctor-route
          uri: lb://medical-provider-doctor
          predicates:
            - Path=/doctor/**
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 47.113.184.197
    password: 123456
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"